// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3it3Z27aAQZ6_adgLT8kNCXld3XDZ_pU',
    appId: '1:637970082188:web:57304b8bf42aa244444ea9',
    messagingSenderId: '637970082188',
    projectId: 'naco-d2738',
    authDomain: 'naco-d2738.firebaseapp.com',
    storageBucket: 'naco-d2738.firebasestorage.app',
    measurementId: 'G-748HFHLPTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb2BvS6Afzkg418J5xMNfaGQIVPICgx7Q',
    appId: '1:637970082188:android:5826df17b039c5a3444ea9',
    messagingSenderId: '637970082188',
    projectId: 'naco-d2738',
    storageBucket: 'naco-d2738.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwymlZBjsPY8YyTmpgGO_dQOW-8diylYM',
    appId: '1:637970082188:ios:df5adc32bc9703e4444ea9',
    messagingSenderId: '637970082188',
    projectId: 'naco-d2738',
    storageBucket: 'naco-d2738.firebasestorage.app',
    iosBundleId: 'com.example.artisanMarketplaceNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwymlZBjsPY8YyTmpgGO_dQOW-8diylYM',
    appId: '1:637970082188:ios:df5adc32bc9703e4444ea9',
    messagingSenderId: '637970082188',
    projectId: 'naco-d2738',
    storageBucket: 'naco-d2738.firebasestorage.app',
    iosBundleId: 'com.example.artisanMarketplaceNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3it3Z27aAQZ6_adgLT8kNCXld3XDZ_pU',
    appId: '1:637970082188:web:5a8ada8d2e741949444ea9',
    messagingSenderId: '637970082188',
    projectId: 'naco-d2738',
    authDomain: 'naco-d2738.firebaseapp.com',
    storageBucket: 'naco-d2738.firebasestorage.app',
    measurementId: 'G-5E967ZE5WS',
  );

}