-- Supabase runtime AdMob control (no app release required).
-- Run in SQL Editor once.

create table if not exists public.app_runtime_config (
  id bigint generated by default as identity primary key,
  config_key text not null unique,
  ads_enabled boolean not null default true,
  banner_android text,
  banner_ios text,
  native_android text,
  native_ios text,
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at_app_runtime_config()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_app_runtime_config_updated_at on public.app_runtime_config;
create trigger trg_app_runtime_config_updated_at
before update on public.app_runtime_config
for each row execute function public.set_updated_at_app_runtime_config();

insert into public.app_runtime_config (
  config_key,
  ads_enabled,
  banner_android,
  banner_ios,
  native_android,
  native_ios
)
values (
  'ads',
  true,
  'ca-app-pub-xxxxxxxxxxxxxxxx/banner_android',
  'ca-app-pub-xxxxxxxxxxxxxxxx/banner_ios',
  'ca-app-pub-xxxxxxxxxxxxxxxx/native_android',
  'ca-app-pub-xxxxxxxxxxxxxxxx/native_ios'
)
on conflict (config_key) do update
set
  ads_enabled = excluded.ads_enabled,
  banner_android = excluded.banner_android,
  banner_ios = excluded.banner_ios,
  native_android = excluded.native_android,
  native_ios = excluded.native_ios;

-- Allow read access (required so app can fetch config).
alter table public.app_runtime_config enable row level security;

drop policy if exists "public can read app runtime config" on public.app_runtime_config;
create policy "public can read app runtime config"
on public.app_runtime_config
for select
to authenticated, anon
using (true);

-- If you want only admins to update, do not create update policy for anon/authenticated.
-- Update examples:
-- 1) Disable all ads immediately:
--    update public.app_runtime_config set ads_enabled = false where config_key = 'ads';
-- 2) Re-enable:
--    update public.app_runtime_config set ads_enabled = true where config_key = 'ads';
-- 3) Rotate an ad unit id:
--    update public.app_runtime_config
--    set banner_android = 'ca-app-pub-xxx/new_banner_android'
--    where config_key = 'ads';
