-- Supabase feature flags runtime control.
-- Run once in Supabase SQL editor.

create table if not exists public.app_feature_flags (
  id bigint generated by default as identity primary key,
  config_key text not null unique,
  maintenance_mode boolean not null default false,
  maintenance_message text,
  disable_post_job boolean not null default false,
  disable_bookings boolean not null default false,
  disable_chat boolean not null default false,
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at_app_feature_flags()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_app_feature_flags_updated_at on public.app_feature_flags;
create trigger trg_app_feature_flags_updated_at
before update on public.app_feature_flags
for each row execute function public.set_updated_at_app_feature_flags();

insert into public.app_feature_flags (
  config_key,
  maintenance_mode,
  maintenance_message,
  disable_post_job,
  disable_bookings,
  disable_chat
)
values (
  'global',
  false,
  null,
  false,
  false,
  false
)
on conflict (config_key) do update
set
  maintenance_mode = excluded.maintenance_mode,
  maintenance_message = excluded.maintenance_message,
  disable_post_job = excluded.disable_post_job,
  disable_bookings = excluded.disable_bookings,
  disable_chat = excluded.disable_chat;

alter table public.app_feature_flags enable row level security;

drop policy if exists "public can read app feature flags" on public.app_feature_flags;
create policy "public can read app feature flags"
on public.app_feature_flags
for select
to authenticated, anon
using (true);

-- Toggle examples:
-- Maintenance ON:
-- update public.app_feature_flags
-- set maintenance_mode = true,
--     maintenance_message = 'We are upgrading the platform. Back soon.'
-- where config_key = 'global';

-- Maintenance OFF:
-- update public.app_feature_flags
-- set maintenance_mode = false,
--     maintenance_message = null
-- where config_key = 'global';

-- Disable job posting only:
-- update public.app_feature_flags
-- set disable_post_job = true
-- where config_key = 'global';
