-- Feed Tips (run in Supabase SQL editor once)

create table if not exists public.feed_tips (
  id bigint generated by default as identity primary key,
  user_type text not null default 'all', -- artisan | business | customer | all
  title text,
  tip text not null,
  priority int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.feed_tips enable row level security;

drop policy if exists "public can read active feed tips" on public.feed_tips;
create policy "public can read active feed tips"
on public.feed_tips
for select
to anon, authenticated
using (is_active = true);

-- Track per-user tip seen state
create table if not exists public.feed_tip_reads (
  user_id uuid primary key references public.users(id) on delete cascade,
  last_seen_at timestamptz not null default now()
);

alter table public.feed_tip_reads enable row level security;

create table if not exists public.feed_tip_notification_dispatches (
  tip_id bigint not null references public.feed_tips(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (tip_id, user_id)
);

alter table public.feed_tip_notification_dispatches enable row level security;

drop policy if exists "users can read their tip read state" on public.feed_tip_reads;
create policy "users can read their tip read state"
on public.feed_tip_reads
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "users can upsert their tip read state" on public.feed_tip_reads;
create policy "users can upsert their tip read state"
on public.feed_tip_reads
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create or replace function public.queue_feed_tip_notifications(
  p_tip_id bigint
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tip record;
  v_sent_count integer := 0;
begin
  select
    ft.id,
    coalesce(nullif(trim(ft.title), ''), 'New tip from MSpace') as title,
    trim(ft.tip) as tip,
    coalesce(nullif(lower(trim(ft.user_type)), ''), 'all') as user_type,
    ft.is_active
  into v_tip
  from public.feed_tips ft
  where ft.id = p_tip_id
  limit 1;

  if not found
     or coalesce(v_tip.is_active, false) = false
     or coalesce(v_tip.tip, '') = '' then
    return 0;
  end if;

  with eligible_users as (
    select distinct u.id
    from public.users u
    left join public.user_settings us
      on us.user_id = u.id
    where coalesce(u.moderation_status, 'active') = 'active'
      and coalesce(us.push_notifications, true) = true
      and (
        v_tip.user_type = 'all'
        or lower(coalesce(u.user_type, 'customer')) = v_tip.user_type
        or (
          v_tip.user_type = 'artisan'
          and lower(coalesce(u.user_type, 'customer')) = 'business'
        )
      )
      and exists (
        select 1
        from public.fcm_tokens ft
        where ft.user_id = u.id
      )
  ),
  queued_dispatches as (
    insert into public.feed_tip_notification_dispatches (
      tip_id,
      user_id,
      created_at
    )
    select
      v_tip.id,
      eu.id,
      now()
    from eligible_users eu
    on conflict (tip_id, user_id) do nothing
    returning user_id
  ),
  inserted_notifications as (
    insert into public.notifications (
      user_id,
      title,
      body,
      type,
      read,
      data,
      created_at
    )
    select
      qd.user_id,
      v_tip.title,
      v_tip.tip,
      'system',
      false,
      jsonb_build_object(
        'action', 'open_feed_tips',
        'type', 'tip',
        'subType', 'feed_tip',
        'tipId', v_tip.id,
        'targetUserType', v_tip.user_type
      ),
      now()
    from queued_dispatches qd
    returning 1
  )
  select count(*)
  into v_sent_count
  from inserted_notifications;

  return v_sent_count;
end;
$$;

create or replace function public.handle_feed_tip_publish()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' and coalesce(new.is_active, false) then
    perform public.queue_feed_tip_notifications(new.id);
  elsif tg_op = 'UPDATE'
        and coalesce(old.is_active, false) = false
        and coalesce(new.is_active, false) then
    perform public.queue_feed_tip_notifications(new.id);
  end if;

  return new;
end;
$$;

drop trigger if exists trg_feed_tip_publish on public.feed_tips;
create trigger trg_feed_tip_publish
after insert or update of is_active on public.feed_tips
for each row
execute function public.handle_feed_tip_publish();

-- Example insert:
-- insert into public.feed_tips (user_type, title, tip, priority)
-- values ('business', 'Quick tip', 'Add service categories so clients can find you faster.', 10);
