-- Profile view analytics + periodic digest notifications.
-- Run in Supabase SQL editor once.

create table if not exists public.profile_view_events (
  id bigint generated by default as identity primary key,
  profile_user_id uuid not null references public.users(id) on delete cascade,
  profile_user_type text,
  viewer_user_id uuid references public.users(id) on delete set null,
  viewer_name text,
  viewer_photo_url text,
  viewer_user_type text,
  source text not null default 'app',
  viewed_at timestamptz not null default now()
);

create index if not exists idx_profile_view_events_profile_user
  on public.profile_view_events (profile_user_id, viewed_at desc);

create index if not exists idx_profile_view_events_viewer_user
  on public.profile_view_events (viewer_user_id, viewed_at desc);

create table if not exists public.profile_view_digest_state (
  profile_user_id uuid primary key references public.users(id) on delete cascade,
  last_notified_at timestamptz,
  last_notified_viewed_at timestamptz
);

alter table public.profile_view_events enable row level security;
alter table public.profile_view_digest_state enable row level security;

create or replace function public.log_profile_view(
  p_profile_user_id uuid,
  p_profile_user_type text default null,
  p_viewer_name text default null,
  p_viewer_photo_url text default null,
  p_viewer_user_type text default null,
  p_source text default 'app'
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_viewer_user_id uuid := auth.uid();
begin
  if p_profile_user_id is null then
    return;
  end if;

  if v_viewer_user_id is not null and v_viewer_user_id = p_profile_user_id then
    return;
  end if;

  insert into public.profile_view_events (
    profile_user_id,
    profile_user_type,
    viewer_user_id,
    viewer_name,
    viewer_photo_url,
    viewer_user_type,
    source
  )
  values (
    p_profile_user_id,
    p_profile_user_type,
    v_viewer_user_id,
    p_viewer_name,
    p_viewer_photo_url,
    p_viewer_user_type,
    coalesce(nullif(p_source, ''), 'app')
  );

  -- Queue a notification immediately so closed-app delivery can happen
  -- through the existing notifications -> webhook -> FCM pipeline.
  perform public.queue_profile_view_digest_for_user(p_profile_user_id);
end;
$$;

create or replace function public.get_my_profile_view_summary(
  p_profile_user_id uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_owner_id uuid := coalesce(p_profile_user_id, auth.uid());
  v_total_views bigint := 0;
  v_unique_viewers bigint := 0;
  v_anonymous_views bigint := 0;
  v_last_viewed_at timestamptz;
  v_can_see_viewers boolean := false;
  v_business_has_premium boolean := false;
begin
  if v_owner_id is null or auth.uid() is distinct from v_owner_id then
    return jsonb_build_object(
      'total_views', 0,
      'unique_viewers', 0,
      'anonymous_views', 0,
      'can_see_viewers', false,
      'last_viewed_at', null
    );
  end if;

  select
    count(*),
    count(distinct viewer_user_id),
    count(*) filter (where viewer_user_id is null),
    max(viewed_at)
  into
    v_total_views,
    v_unique_viewers,
    v_anonymous_views,
    v_last_viewed_at
  from public.profile_view_events
  where profile_user_id = v_owner_id;

  select coalesce(
    (select premium from public.artisan_profiles where user_id = v_owner_id limit 1),
    false
  )
  into v_can_see_viewers;

  if not v_can_see_viewers then
    select exists (
      select 1
      from information_schema.columns
      where table_schema = 'public'
        and table_name = 'business_profiles'
        and column_name = 'premium'
    )
    into v_business_has_premium;

    if v_business_has_premium then
      execute
        'select coalesce(premium, false) from public.business_profiles where user_id = $1 limit 1'
      into v_can_see_viewers
      using v_owner_id;
    end if;
  end if;

  return jsonb_build_object(
    'total_views', coalesce(v_total_views, 0),
    'unique_viewers', coalesce(v_unique_viewers, 0),
    'anonymous_views', coalesce(v_anonymous_views, 0),
    'can_see_viewers', coalesce(v_can_see_viewers, false),
    'last_viewed_at', v_last_viewed_at
  );
end;
$$;

create or replace function public.get_my_profile_viewers(
  p_profile_user_id uuid default null
)
returns table (
  viewer_user_id uuid,
  viewer_name text,
  viewer_photo_url text,
  viewer_user_type text,
  total_views bigint,
  last_viewed_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_owner_id uuid := coalesce(p_profile_user_id, auth.uid());
  v_can_see_viewers boolean := false;
  v_business_has_premium boolean := false;
begin
  if v_owner_id is null or auth.uid() is distinct from v_owner_id then
    return;
  end if;

  select coalesce(
    (select premium from public.artisan_profiles where user_id = v_owner_id limit 1),
    false
  )
  into v_can_see_viewers;

  if not v_can_see_viewers then
    select exists (
      select 1
      from information_schema.columns
      where table_schema = 'public'
        and table_name = 'business_profiles'
        and column_name = 'premium'
    )
    into v_business_has_premium;

    if v_business_has_premium then
      execute
        'select coalesce(premium, false) from public.business_profiles where user_id = $1 limit 1'
      into v_can_see_viewers
      using v_owner_id;
    end if;
  end if;

  if not coalesce(v_can_see_viewers, false) then
    return;
  end if;

  return query
  select
    pve.viewer_user_id,
    coalesce(max(nullif(pve.viewer_name, '')), 'Anonymous viewer') as viewer_name,
    max(pve.viewer_photo_url) as viewer_photo_url,
    max(pve.viewer_user_type) as viewer_user_type,
    count(*) as total_views,
    max(pve.viewed_at) as last_viewed_at
  from public.profile_view_events pve
  where pve.profile_user_id = v_owner_id
    and pve.viewer_user_id is not null
  group by pve.viewer_user_id
  order by max(pve.viewed_at) desc;
end;
$$;

create or replace function public.queue_profile_view_digest_for_user(
  p_profile_user_id uuid
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_last_notified_at timestamptz;
  v_last_notified_viewed_at timestamptz;
  v_new_views bigint := 0;
  v_unique_viewers bigint := 0;
  v_latest_viewed_at timestamptz;
  v_title text;
  v_body text;
begin
  if p_profile_user_id is null then
    return false;
  end if;

  select
    last_notified_at,
    last_notified_viewed_at
  into
    v_last_notified_at,
    v_last_notified_viewed_at
  from public.profile_view_digest_state
  where profile_user_id = p_profile_user_id;

  if v_last_notified_at is not null
     and v_last_notified_at > now() - interval '24 hours' then
    return false;
  end if;

  select
    count(*),
    count(distinct viewer_user_id),
    max(viewed_at)
  into
    v_new_views,
    v_unique_viewers,
    v_latest_viewed_at
  from public.profile_view_events
  where profile_user_id = p_profile_user_id
    and viewed_at > coalesce(v_last_notified_viewed_at, to_timestamp(0));

  if coalesce(v_new_views, 0) = 0 or v_latest_viewed_at is null then
    return false;
  end if;

  v_title := 'Your profile is getting attention';
  v_body := case
    when v_unique_viewers > 0 then
      'You got ' || v_new_views || ' new profile view' ||
      case when v_new_views = 1 then '' else 's' end ||
      ' from ' || v_unique_viewers || ' viewer' ||
      case when v_unique_viewers = 1 then '' else 's' end ||
      '. Tap to see the details.'
    else
      'You got ' || v_new_views || ' new profile view' ||
      case when v_new_views = 1 then '' else 's' end ||
      '. Tap to see the details.'
  end;

  insert into public.notifications (
    user_id,
    title,
    body,
    type,
    read,
    data,
    created_at
  )
  values (
    p_profile_user_id,
    v_title,
    v_body,
    'system',
    false,
    jsonb_build_object(
      'action', 'open_profile_analytics',
      'type', 'profile_view',
      'subType', 'profile_view_digest',
      'newViews', v_new_views,
      'uniqueViewers', v_unique_viewers
    ),
    now()
  );

  insert into public.profile_view_digest_state (
    profile_user_id,
    last_notified_at,
    last_notified_viewed_at
  )
  values (
    p_profile_user_id,
    now(),
    v_latest_viewed_at
  )
  on conflict (profile_user_id) do update
  set
    last_notified_at = excluded.last_notified_at,
    last_notified_viewed_at = excluded.last_notified_viewed_at;

  return true;
end;
$$;

create or replace function public.send_my_profile_view_digest()
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    return false;
  end if;

  return public.queue_profile_view_digest_for_user(auth.uid());
end;
$$;

create or replace function public.send_profile_view_digests()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row record;
  v_sent_count integer := 0;
begin
  for v_row in
    select distinct profile_user_id
    from public.profile_view_events
  loop
    if public.queue_profile_view_digest_for_user(v_row.profile_user_id) then
      v_sent_count := v_sent_count + 1;
    end if;
  end loop;

  return v_sent_count;
end;
$$;

grant execute on function public.log_profile_view(uuid, text, text, text, text, text)
  to authenticated, anon;

grant execute on function public.get_my_profile_view_summary(uuid)
  to authenticated;

grant execute on function public.get_my_profile_viewers(uuid)
  to authenticated;

grant execute on function public.send_my_profile_view_digest()
  to authenticated;

-- Optional: run this from pg_cron or Supabase scheduled jobs every hour.
-- select cron.schedule(
--   'profile-view-digests-hourly',
--   '5 * * * *',
--   $$select public.send_profile_view_digests();$$
-- );
