-- Referrals + Business Profiles setup
-- Run in Supabase SQL editor once.

-- 1) Referral codes (one per user)
create table if not exists public.referral_codes (
  user_id uuid primary key references public.users(id) on delete cascade,
  code text not null unique,
  created_at timestamptz not null default now()
);

-- 2) Referral attributions (who referred whom)
create table if not exists public.referral_attributions (
  id bigint generated by default as identity primary key,
  referrer_id uuid not null references public.users(id) on delete cascade,
  referred_user_id uuid not null references public.users(id) on delete cascade,
  source text,
  created_at timestamptz not null default now(),
  constraint referral_attributions_unique_referred unique (referred_user_id)
);

create index if not exists referral_attributions_referrer_idx
  on public.referral_attributions (referrer_id);

-- 3) Business profiles
create table if not exists public.business_profiles (
  user_id uuid primary key references public.users(id) on delete cascade,
  business_name text not null,
  service_categories text[] not null default '{}',
  team_size int,
  coverage_area text,
  logo_url text,
  description text,
  contact_phone text,
  show_phone boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.business_profiles
  add column if not exists show_phone boolean not null default false;

create or replace function public.set_updated_at_business_profiles()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_business_profiles_updated_at on public.business_profiles;
create trigger trg_business_profiles_updated_at
before update on public.business_profiles
for each row execute function public.set_updated_at_business_profiles();

-- 4) Business items (products/services sold)
create table if not exists public.business_items (
  id bigint generated by default as identity primary key,
  business_id uuid not null references public.business_profiles(user_id) on delete cascade,
  name text not null,
  description text,
  price text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at_business_items()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_business_items_updated_at on public.business_items;
create trigger trg_business_items_updated_at
before update on public.business_items
for each row execute function public.set_updated_at_business_items();

-- 5) Leaderboard view
create or replace view public.referral_leaderboard as
select
  referrer_id,
  count(*)::int as total_referrals
from public.referral_attributions
group by referrer_id
order by total_referrals desc;

-- Enable RLS
alter table public.referral_codes enable row level security;
alter table public.referral_attributions enable row level security;
alter table public.business_profiles enable row level security;
alter table public.business_items enable row level security;

-- Referral codes policies
drop policy if exists "public can read referral codes" on public.referral_codes;
create policy "public can read referral codes"
on public.referral_codes
for select
to anon, authenticated
using (true);

drop policy if exists "users can manage their referral code" on public.referral_codes;
create policy "users can manage their referral code"
on public.referral_codes
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- Referral attribution policies
drop policy if exists "public can read referral leaderboard" on public.referral_attributions;
create policy "public can read referral leaderboard"
on public.referral_attributions
for select
to anon, authenticated
using (true);

drop policy if exists "users can insert referral attribution for themselves" on public.referral_attributions;
create policy "users can insert referral attribution for themselves"
on public.referral_attributions
for insert
to authenticated
with check (auth.uid() = referred_user_id);

-- Business profiles policies
drop policy if exists "public can read business profiles" on public.business_profiles;
create policy "public can read business profiles"
on public.business_profiles
for select
to anon, authenticated
using (true);

drop policy if exists "users can manage their business profile" on public.business_profiles;
create policy "users can manage their business profile"
on public.business_profiles
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- Business items policies
drop policy if exists "public can read business items" on public.business_items;
create policy "public can read business items"
on public.business_items
for select
to anon, authenticated
using (true);

drop policy if exists "business owners can manage items" on public.business_items;
create policy "business owners can manage items"
on public.business_items
for all
to authenticated
using (auth.uid() = business_id)
with check (auth.uid() = business_id);
